{% set name = "langextract" %}
{% set version = "1.0.6" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langextract-{{ version }}.tar.gz
  sha256: 97793c7a12c972e5b630110fffb4a7cd71a7e9b316ae0e92f1933b90c3a63a29

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=67.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - absl-py >=1.0.0
    - aiohttp >=3.8.0
    - async-timeout >=4.0.0
    - exceptiongroup >=1.1.0
    - google-genai >=0.1.0
    - ml-collections >=0.1.0
    - more-itertools >=8.0.0
    - numpy >=1.20.0
    - openai >=0.27.0
    - pandas >=1.3.0
    - pydantic >=1.8.0
    - python-dotenv >=0.19.0
    - requests >=2.25.0
    - tqdm >=4.64.0
    - typing_extensions >=4.0.0

test:
  imports:
    - langextract
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/google/langextract
  summary: 'LangExtract: A library for extracting structured data from language models'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
